### ISSUE TITLE
HUGGINGFACEHUB_API_TOKEN=<YOUR_API_KEY_HERE>

### ISSUE THREAD

**Issue by luxiart** [DEENUU1/meta-spy#371]
Noob question : How do I get my huggingface hub api token to put in env. ? thanks

**Comment by DEENUU1** [comment]
Go to this url https://huggingface.co/settings/tokens and create a new token key 


You don't need to put this API KEY into the .env file, only 1 command is using this and I am planning to delete that

**Comment by luxiart** [comment]
thanks

but i can go through this error : "

*Did not find huggingfacehub_api_token, please add an environment variable
`HUGGINGFACEHUB_API_TOKEN` which contains it, or pass
 `huggingfacehub_api_token` as a named parameter. (type=value_error)*

Thanks in advance for your help

Le sam. 4 nov. 2023 à 13:35, Kacper Włodarczyk ***@***.***> a
écrit :
